### ISSUE TITLE
Creación de repositorio para proyecto de página de salud y bienestar

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#1]
Hola Equipo!!!

Necesitamos crear un nuevo repositorio en Git para nuestro proyecto de página de salud y bienestar centrada en dietas saludables y seguimiento de alimentación. Esta issue servirá como seguimiento y documentación del proceso de creación del repositorio.

**Tareas a realizar**
1. Inicializar un nuevo repositorio en Git.
2. Configurar la estructura de directorios para el proyecto, considerando secciones como Inicio, Registrarme, Servicios, Recetas, Testimonios, Contáctanos, Gestión de datos.
3. Establecer la estructura de ramas (branches) para el desarrollo, como una rama principal (main) y ramas de características (feature branches) para cada funcionalidad importante.
4. Agregar el archivo README.md con información básica sobre el proyecto.
5. Compartir los enlaces y permisos necesarios para que los colaboradores puedan acceder al repositorio.

Saludos!!

**Comment by NaimaFarja** [comment]
Estimados compañeros:
Quisiera informarles que he creado el repositorio "Grupo23_TPFinal" destinado a nuestro trabajo práctico final. Asimismo, he configurado los permisos necesarios para que @marisolpatri77 pueda asignarnos las tareas a medida que avancemos en este proyecto. Por tanto, procederé a cerrar esta tarea.
Agradezco su atención y colaboración en este proceso.
Saludos!!
