### ISSUE TITLE
Creación de archivos recetas.html y servicios.html

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#10]
Hola Naima!!
La tarea asignada implica la creación de una nueva rama con el objetivo de desarrollar dos archivos HTML dentro de la carpeta "templates": "recetas.html" para agregar recetas saludables y "servicios.html" donde los usuarios podrán calcular su IMC (Índice de Masa Corporal) y peso ideal.

**Comment by NaimaFarja** [comment]
Buenas noches Grupo23.
Ya termine de armar los HTML "recetas.html" y "servicios.html" seleccionados para mi tarea.
