### ISSUE TITLE
Creación de los formularios html logininicio y loginregistro

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#11]
Hola Sofia!!
Se te ha asignado la tarea de crear dos ramas nuevas para implementar dos formularios específicos. La primera rama estará destinada al desarrollo del formulario de inicio de sesión. La segunda rama se enfocará en el formulario de registro de usuarios.

**Comment by Sofi231098** [comment]
Hola equipo, ya termine los html de logueo y registro, ya podemos pasar a la otra tarea.
