### ISSUE TITLE
Rama develop

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#12]
Creacion de nueva rama
Esta tarea esta destinada a la creacion de una rama denominada "develop" la cual sera una rama de respaldo y prueba, con la que fusionaremos las ramas nuevas para evitar conflictos con la rama principal "main". una vez que se verifique que no hay errores la misma rama "develop" sera fusionada con la rama principal "main"

**Comment by Flores-Fabricio-Alfredo** [comment]
Hola buenas noches compañeros ya cree la rama develop que va a funcionar como una rama de respaldo y prueba, para no generar conflictos con la rama main
