### ISSUE TITLE
Fusion de las ramas nuevas con rama de prueba 

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#13]
Fusión de la rama "develop":
Esta tarea implica fusionar todas las ramas nuevas creadas por los usuarios del Grupo 23 con el fin de probar el funcionamiento de la página. Si todo está correcto, se procederá a fusionar la rama de pruebas y respaldo "develop" con la rama principal "main".

**Comment by Flores-Fabricio-Alfredo** [comment]
Hola buenas noches compañeros @marisolpatri77 @Sofi231098 @NaimaFarja @Lguerrero2023 ya fusione las ramas  para que puedan seguir trabajando.
Saludos
