### ISSUE TITLE
Dependencias en el archivo pom.

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#17]
Estimada Sofía,
Te informo que se te ha asignado la tarea de agregar las siguientes dependencias:
webjav: para utilizar las versiones de Bootstrap.
bootstrap: para añadir estilos a la página.
Validaciones
MySql: para establecer la conexión con la base de datos.
El objetivo de esta tarea es permitir que nuestros compañeros puedan empezar a editar sus archivos HTML y trabajar con las nuevas dependencias.
Saludos cordiales.

**Comment by Sofi231098** [comment]
Buenas, ya agregué las dependencias que me pidieron al archivo pom.xml. Estan comentadas para evitar warnings y errores, deben descomentarlas para trabajar.
