### ISSUE TITLE
Fusion con rama de prueba "develop"

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#18]
Buenas tardes Naima,
Se te ha asignado la tarea de fusionar la nueva rama "dependencias", creada por @Sofi231098, con la rama de respaldo y pruebas "develop". Esta fusión permitirá que los demás usuarios del Grupo23 puedan trabajar con las nuevas dependencias agregadas en el archivo pom.
Saludos cordiales.

**Comment by NaimaFarja** [comment]
Estimados compañeros,
Realice con exito la fusion de la rama "depedencias" con la rama de pruebas y respaldo develop.
Saludos cordiales.
