### ISSUE TITLE
Crear carpeta css

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#20]
Buenas tardes Sofía,
Quiero informarte que se te ha asignado la tarea de crear la carpeta "css" dentro de la carpeta "static". Esta nueva carpeta debe contener un archivo CSS que permitirá editar y agregar estilos diferentes a los archivos HTML.

**Comment by Sofi231098** [comment]
hola, ya hice la carpeta y el archivo css para trabajar con el estilo, pueden fusionar esta rama a la develop
