### ISSUE TITLE
Creacion de las capas, Controller, Model y listas

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#25]
Buenas noches Fabricio,
Se te ha asignado la creación de las siguientes capas dentro de nuestra aplicación:
Capa del Controlador (Controller): Esta capa es esencial para recibir las solicitudes de los usuarios, coordinar las acciones necesarias y proporcionar respuestas adecuadas. Su función es crucial en la comunicación entre el cliente y el sistema, asegurando un flujo de trabajo eficiente y satisfactorio.
Capa del Modelo (Model): En esta capa, nos centraremos en representar los objetos de dominio y la lógica empresarial de nuestra aplicación. Definiremos clases que encapsulen los datos y los comportamientos relacionados con ellos. Esta capa nos permitirá establecer una estructura sólida para la gestión de la información y asegurar la integridad de los datos.
Capa de Listas: Enfocada en el desarrollo de clases y estructuras de datos eficientes, esta capa se encargará de almacenar y manipular colecciones de elementos de manera optimizada. La selección adecuada de las estructuras de datos asegurará un rendimiento óptimo y una gestión eficiente de los datos almacenados.

**Comment by Flores-Fabricio-Alfredo** [comment]
Hola buenas noches, ya creer las capas solicitada.
