### ISSUE TITLE
Fusion rama "Creacion_la_Capa_Controller" con la rama "develop"

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#26]
Se te ha asignado la tarea de fusionar la nueva rama, con la rama de respaldo y pruebas "develop". Esta fusión permitirá que los demás usuarios del Grupo23 puedan trabajar con las nuevos paquetes java agregados.
Saludos cordiales.

**Comment by Flores-Fabricio-Alfredo** [comment]
Tarea realizada ya pueden descargar la modificación de la rama develop. 
Saludos.
