### ISSUE TITLE
Modificaciones

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#31]
Buenas tardes Fabricio,
La tarea consiste en adaptar los archivos HTML existentes para incorporar la funcionalidad de Thymeleaf  ya que este es un motor de plantillas diseñado para aplicaciones web Java que permite combinar código HTML y Java en las vistas.

**Comment by Flores-Fabricio-Alfredo** [comment]
hola buenas tardes tarea realizada, ya pueden descargar la ultima versión de la develop compañeros: @marisolpatri77  @Sofi231098 @NaimaFarja @Lguerrero2023
