### ISSUE TITLE
Creación de archivos inicio.html

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#8]
Hola Fabricio!!
Se te ha asignado la tarea de crear una nueva rama para añadir el archivo HTML "inicio" en la carpeta templates, que contendrá información relevante para la página, además de otros elementos comunes en el inicio de una página, como el encabezado, menú de navegación y pie de página.

**Comment by Flores-Fabricio-Alfredo** [comment]
Hola buenas noches estimados compañeros ya cree y subí el archivo inicio.html, con la información básica de la pagina
