### ISSUE TITLE
Creación de archivos testimonios.html

### ISSUE THREAD

**Issue by marisolpatri77** [NaimaFarja/Grupo23_TPFinal#9]
Holaa Luis.
Se te asigna la tarea de crear una nueva rama con un nombre descriptivo, específicamente destinada a la creación del archivo HTML "testimonios". El objetivo es que puedas trabajar en dicho archivo y realizar las ediciones necesarias para su desarrollo.

**Comment by Lguerrero2023** [comment]
Estimados compañeros de grupo,
Quiero informarles que he completado exitosamente la tarea asignada. He subido mi rama y archivo al proyecto, por lo que ahora están disponibles para su revisión.
